name = "seo-tools-platform"
compatibility_date = "2026-04-27"
pages_build_output_dir = "./dist"

[[kv_namespaces]]
binding = "SEO_TOOLS_KV"
id = "40b3a293f827401ea0360df1defe4007"

[browser]
binding = "BROWSER"

[ai]
binding = "AI"
